### ISSUE TITLE
No documention on connecting metamask to the kovan test network

### ISSUE THREAD

**Issue by rabble** [DevanaLabs/lemon.email-dApp#2]
So, to try this out, you install metamask, and then try and load lemonmail... but dude, you get a message saying connect to the kovan test network... no link, no documentation, how the hell do you do that? googling and reading half a dozen pages doesn't enlighten.

**Comment by andrejc** [comment]
When you open the main MetaMask window, there is a text that should say "Main Ethereum Network" in the top left corner (just next to the fox icon). If you click on it, it should display a drop-down menu where you can then select "Kovan Test Net". Please let me know if you are still having issues.
