### ISSUE TITLE
Integrity Checksum failed

### ISSUE THREAD

**Issue by lsaether** [DevanaLabs/lemon.email-dApp#3]
Got the following error after cloning and trying to run npm install on the repo. What does it mean?

npm ERR! code EINTEGRITY
npm ERR! sha1-8/zKCm/gZzanulcpZgaWF8EwtIE= integrity checksum failed when using sha1: wanted sha1-8/zKCm/gZzanulcpZgaWF8EwtIE= but got sha1-PnrIJ5Q30Z/xuOeqIq48KWQuZn0=. (2238 bytes)

**Comment by Cordo-van-Saviour** [comment]
I believe that this is the problem with some `npm` package, not with the Lemon DApp itself. Can you add more error info? Also, please add information about the OS.
