### ISSUE TITLE
cannot login to website

### ISSUE THREAD

**Issue by kleytr6s** [DevanaLabs/lemon.email-dApp#4]
I have not been able to check my email for 3-5 days. The lemon.email and webmail.lemon.email sites are not reachable. Why? Sorry to place this as an issue on github, but their are no other places for support. What are the server addresses, port numbers, encryption, etc. used for inboxes and sent messages? I am asking because i want to try to log in through an email client.

**Comment by andrejc** [comment]
Hi,

Please keep in mind that Lemon Mail DApp is separate product from lemon.email (i.e. the DApp is open-source, has no servers and no owner).

As far as I know, the company that was behind lemon.email service no longer exists and that is probably a reason why you cannot access the website. I don't know why they didn't shut down gracefully (e.g. why they didn't notify customers about it). If the emails you had stored there are really important to you, I could connect you with people who might still have access to the servers and see if they could retrieve your emails for you.

**Comment by andrejc** [comment]
The service should be back online now: https://lemon.email
